package com.gz.p2p.mapper.loan;

import com.gz.p2p.model.loan.BidInfo;
import com.gz.p2p.model.user.BidUserVO;

import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int updateByPrimaryKey(BidInfo record);


    Double selectAllBidMoney();

    List<BidInfo> selectBidInfoById(Map<String, Object> param);

    List<BidUserVO> selectAllBidUser();

    List<BidInfo> selectBidInfoByLoanInfoId(Integer id);
}