package com.gz.p2p.mapper.loan;

import com.gz.p2p.model.loan.LoanInfo;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon May 09 21:42:35 CST 2022
     */
    int updateByPrimaryKey(LoanInfo record);

    Double selectHistoryAvgRate();

    List<LoanInfo> selectLoanInfoByProductType(Map<String, Integer> param);

    Integer selectTotalSize(Map<String, Integer> param);

    int updateLeftProductMoney(Map<String, Object> param);

    List<LoanInfo> selectLoanInfoByProductStatus(int status);
}